version: '3.3'

services:
 db:
  image: mysql:5.7
  volumes:
   - wp_data:/home/mshelto/dbdata
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: insert Password here
   MYSQL_DATABASE: wordpressDB
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: insert Password here
   
wordpress:
 depends_on:
  - db
 image: wordpress:latest
 ports:
  - "8000:80"
 restart: always
 environment:
  WORDPRESS_DB_HOST: db:3306
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: insert Password here
  WORDPRESS_DB_NAME: werobressDB
volumes:
 wp_data: {}
